### ISSUE TITLE
Error polling interface on POE switch

### ISSUE THREAD

**Issue by networkRob** [networkRob/eos-html-intf#1]
On a CCS-720XP, an error occurs when it appears to be grabbing POE information on a vlan interface.
```
$ swIntf
Traceback (most recent call last):
  File "/usr/bin/swIntf", line 337, in <module>
    lo_sw = lSwitch()
  File "/usr/bin/swIntf", line 92, in __init__
    self.getData()
  File "/usr/bin/swIntf", line 107, in getData
    self.swInfo['interfaces'] = self.evalIntfs()
  File "/usr/bin/swIntf", line 188, in evalIntfs
    tmpDict['poePriority'] = poeIntfs[intf]['portPriority']
KeyError: 'portPriority'
```

**Comment by networkRob** [comment]
Error isn’t from a clan intf, as those are not parsed through.  Only Ethernet, port-channels and mgmt interfaces. 

Going to get further information from the ‘show poe‘ cmd. 

Switch is running EOS-4.21.6F

**Comment by networkRob** [comment]
In 4.21.6F, the key/value pair for `portPriority` is not present.
